USE [master]
GO

/****** Object:  Database [ExaminationSystem]    Script Date: 1/16/2024 5:15:45 PM ******/
CREATE DATABASE [ExaminationSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ExaminationSystem-Data', FILENAME = N'D:\ITI\SQL PROJECT\ExaminationSystem-Data.mdf' , SIZE = 10240KB , MAXSIZE = 51200KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'ExaminationSystem_Log', FILENAME = N'D:\ITI\SQL PROJECT\ExaminationSystem_Log.ldf' , SIZE = 5120KB , MAXSIZE = 40960KB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ExaminationSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ExaminationSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ExaminationSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ExaminationSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ExaminationSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ExaminationSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [ExaminationSystem] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ExaminationSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ExaminationSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ExaminationSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ExaminationSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ExaminationSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ExaminationSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ExaminationSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ExaminationSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ExaminationSystem] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ExaminationSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ExaminationSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ExaminationSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ExaminationSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ExaminationSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ExaminationSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ExaminationSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ExaminationSystem] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ExaminationSystem] SET  MULTI_USER 
GO

ALTER DATABASE [ExaminationSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ExaminationSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ExaminationSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ExaminationSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ExaminationSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ExaminationSystem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ExaminationSystem] SET QUERY_STORE = ON
GO

ALTER DATABASE [ExaminationSystem] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [ExaminationSystem] SET  READ_WRITE 
GO


